### ISSUE TITLE
`?`(ヘルプ表示ショートカット)入力時、既にヘルプページタブが開いていれば、そのタブに移動したい

### ISSUE THREAD

**Issue by sh1ma** [arrow2nd/nekome#37]
こんにちは、フォローしている人がスターしてるのを見て使い始めました！使いやすくて好きです
https://twitter.com/altalkalta/status/1559397869022760960

### なんのissue？

ヘルプ表示ショートカット押下時の挙動の変更

## 現状

ヘルプページが既に開いている場合には`this page already exists`というエラーを出力しています。

## 自分の意見

この場合においては、既に存在するヘルプページタブがあればそっちに移動するのがユーザー体験的にいいのかなという印象を持ちました。もしよかったらご意見頂けると嬉しいです！

## 意見を通す場合に想定される対応

全てのページのタブについて既に開いてあるものが存在する場合に移動処理を挟むとしたら、`app/view.go`の115行目を変更すれば難しくはなさそうだと感じました。
https://github.com/arrow2nd/nekome/blob/main/app/view.go#L115

**Comment by arrow2nd** [comment]
ご丁寧にありがとうございます 🐈

確かに、その挙動の方がストレスが無くてよさそうですね！

**Comment by arrow2nd** [comment]
![demo](https://user-images.githubusercontent.com/44780846/184823130-ef52ccda-78f2-4c71-a121-7e3bce50f6c9.gif)

ヘルプページだけというのもアレなので、共通で「重複するページが作成された場合、既にあるページに移動する」という挙動にしてみました

**Comment by sh1ma** [comment]
うおおお！！迅速な対応ありがとうございます！　めっちゃよさそうです🚀

**Comment by arrow2nd** [comment]
こちらこそ、貴重なご意見ありがとうございました！！
次のリリースまで少々お待ちください... 🐶
