### ISSUE TITLE
補完とカーソルの動作を変更

### ISSUE THREAD

**Issue by arrow2nd** [arrow2nd/nekome#52]
- [x] スクロールが上端に到達すると下端に飛ばずにそこで止まってほしい
- [x] `:<tab>` とタイプした時にコマンド一覧が補完されてほしい

_Originally posted by @ompugao in https://github.com/arrow2nd/nekome/issues/13#issuecomment-1264545308_

**Comment by arrow2nd** [comment]
🚀

![demo](https://user-images.githubusercontent.com/44780846/193443671-020666e6-e43d-4b54-8734-53a3ebc58cd8.gif)

**Comment by ompugao** [comment]
もうですか!? ありがとうございます!!
