### ISSUE TITLE
ツイートのレイアウトをカスタマイズ可能にしたい

### ISSUE THREAD

**Issue by arrow2nd** [arrow2nd/nekome#53]
あともう一点わがままなのですが、
個人的にはもっと1ツイートをコンパクトに表示したくて、目下layout_tweet.goやtweets.goで規定されるレイアウトをいじって利用させてもらっています。
(具体的には"投稿日時・投稿元クライアント"をuserinfoの右側におき、ツイート間のseparatorを消しています)
レイアウトの設定をユーザー側でできるようになると嬉しいです。
https://github.com/arrow2nd/nekome/compare/main...ompugao:nekome:feature/compact_layout

要望ばかり投げつけていて恐縮です…

_Originally posted by @ompugao in https://github.com/arrow2nd/nekome/issues/13#issuecomment-1264608218_

**Comment by arrow2nd** [comment]
### やること

- [ ] ツイート間のセパレータを on/off
- [ ] ユーザ詳細, ツイート本文, 投票詳細, ツイート詳細, リアクション数 のレイアウトのカスタマイズ
- [ ] `createTweetLayout()` で決め打ちしているレイアウトのカスタマイズ

**Comment by arrow2nd** [comment]
ご提案ありがとうございます 😺

レイアウトのカスタマイズ、とても良さそうですね！

[v2.0.0](https://github.com/arrow2nd/nekome/blob/v2/CHANGELOG.md#unreleased) にキーバインドのカスタマイズを実装したところだったので、タイミング的にちょうどいい感じがしました

**Comment by arrow2nd** [comment]
`layout` 以下の設定を変更することで、ツイートとユーザプロフィールのレイアウトをカスタマイズできるようにしてみました

表現がかなり内部寄りなのでわかりにくいかも...と思ったりもしましたが、その代わり自由度はそこそこあるはずです...！

![demo](https://user-images.githubusercontent.com/44780846/193569550-c1b15b90-0a2e-42d8-9b02-3969daabdab0.png)

**Comment by ompugao** [comment]
素早い対応ありがとうございます！ とても満足しています〜
