### ISSUE TITLE
スペースを含むツイートを""で囲まずにツイートしたい

### ISSUE THREAD

**Issue by ompugao** [arrow2nd/nekome#62]
## nekome version
2.0.3

## 現状の挙動

コマンドラインからスペースを含むツイートをしようとするとスペース以降の文字列が無視されます。

例えば
コマンドラインで
```
:tweet abc def
```
とツイートしようとすると
```
abc
```
がツイートされます。

## 求める挙動
```
abc def
```
とツイートされてほしいです。

**Comment by arrow2nd** [comment]
`"` で囲むの確かに手間なので良いなと思いました…！
