### ISSUE TITLE
スペースを含む文字列を""で囲わずにツイート検索したい

### ISSUE THREAD

**Issue by ompugao** [arrow2nd/nekome#65]
#62 と同様、コマンドラインからスペースを含む文字列を検索しようとする`:search abc def`と、
```
[ERR: Command] accepts 1 arg(s), received X
```
となるので、全ての文字列を受け取ってほしいです。

**Comment by arrow2nd** [comment]
`tweet` と同様にこちらも対応しました
issue & PR ありがとうございました！🐈
