### ISSUE TITLE
[不具合報告] 内部ツイートeditorで、キーバインドされているキー(hやl等)が入力できない

### ISSUE THREAD

**Issue by ompugao** [arrow2nd/nekome#67]
nekome version: v2.0.3

内容: 内部エディタでツイート編集中に、例えばhやlを入力しようとタブ移動が発生してしまいます。

**Comment by arrow2nd** [comment]
こちら、私の環境

- OS: macOS 12.6 (Intel)
- ターミナルエミュレータ: kitty, 標準のターミナル

では再現出来なかったのですが、使用されているOSとターミナルエミュレータを教えていただけますでしょうか...？

**Comment by ompugao** [comment]
- OS: Ubuntu 20.04.5 
- ターミナルエミュレータ: kitty v0.26.3およびgnome-terminal (v3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD)

で再現します。 preferences.tomlはnekome editで生成されたものそのままを使用しています。

**Comment by arrow2nd** [comment]
実機にて同じ条件の環境を作成し確認してみたのの、再現できませんでした

内部ツイートエディタを開く際に、アプリ全体のキーバインドを無効化するフラグを立てているので、何か問題があるとすればそこだと思うのですが...
https://github.com/arrow2nd/nekome/blob/843378ec3e755921278132ea1f01ffe7555b6e8b/app/view.go#L311

応急処置としては

1. `keybinding.global / view` 内の該当するキーバインドを変更する
2.  `feature.use_external_editor` を `true` にして外部エディタを使用する

のいずれかで回避できるかなと思います

**Comment by ompugao** [comment]
承知しました。もう少し細かな再現条件を探します。

`feature.use_external_editor = true`で問題なく利用できていますのでさしあたって大丈夫です。

**Comment by arrow2nd** [comment]
コマンドラインから`:tweet` で内部エディタを開くと再現できました（普段キーバインドで開いているので気がつきませんでした...）

**Comment by arrow2nd** [comment]
修正しました 🐈

![fixed](https://user-images.githubusercontent.com/44780846/195242271-3bd0f3a9-ead2-499b-87e8-fd7102736b16.gif)
