### ISSUE TITLE
urlをopenしたときのwebブラウザのログによる描画の崩れを避けたい

### ISSUE THREAD

**Issue by ompugao** [arrow2nd/nekome#86]
ctrl+lによる再描画が必要になるのがurlを開いたときのブラウザによるログでstdout/stderrが流れた時なのですが、その再描画をするのが面倒に感じます。
以下のように捨てるか、bytes.Bufferに貯めてエラー発生時のみ表示するような変更を入れて頂くことは可能でしょうか？
```go
browser.Stdout = io.Discard  // ←
browser.Stderr = io.Discard  // ←
if err := browser.OpenURL(url); err != nil {
	shared.SetErrorStatus("Open", err.Error())
	return
}
```

**Comment by arrow2nd** [comment]
貯めておいても表示する領域が無い（新規にページを開く程でも無い気がする）ので、ログを捨てる形で対応しました。
ご提案ありがとうございました 🐱

**Comment by ompugao** [comment]
ありがとうございます！
